<?=$this->fetch('header.phtml')?>

<div class="container my-5">
    <h1>Анализатор страниц</h1>
    <div class="col-lg-8 px-0">
        <p class="fs-5">Бесплатно проверяйте сайты на SEO пригодность</p>
    <form method="post" action="/urls">
        <div class="mb-2">
            <div class="input-group" style="gap: 0.5rem;">
                <input name="url[name]" type="text" class="form-control" placeholder="https://example.com" id="basic-url" aria-describedby="basic-addon3 basic-addon4">
                <button type="submit" class="btn btn-primary">Проверить</button>
            </div>

        </div>
    </form>
    </div>
</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/js/bootstrap.bundle.min.js" integrity="sha384-FKyoEForCGlyvwx9Hj09JcYn3nv7wiPVlz7YYwJrWVcXK/BmnVDxM+D2scQbITxI" crossorigin="anonymous"></script>
<script src="main.js"></script>
</body>
</html>