<?=$this->fetch('header.phtml')?>
<div class="container-lg mt-3">
    <h1><?= $name; ?></h1>
    <div class="table-responsive">
        <table class="table table-bordered table-hover text-nowrap" data-test="url">
            <tbody>
            <tr>
                <td>ID</td>
                <td><?= $id ?></td>
            </tr>
            <tr>
                <td>Имя</td>
                <td><?= $name; ?></td>
            </tr>
            <tr>
                <td>Дата создания</td>
                <td><?= $created_at; ?></td>
            </tr>
            </tbody>
        </table>
    </div>
    <?php if (!empty($succes)) : ?>
    <small class="text-danger">
        <?= htmlspecialchars($succes[0]); ?>
    </small>
    <?php endif; ?>
</div>
